"""Export the OpenAPI document.

uv run python -m app.openapi_schema           # rewrite openapi.yaml
uv run python -m app.openapi_schema --check   # exit 1 if openapi.yaml drifted (CI)
"""

import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

from app.config import ROOT, Settings
from app.main import create_app

SPEC_PATH = ROOT / "openapi.yaml"


def build() -> dict[str, Any]:
    with tempfile.TemporaryDirectory() as tmp:
        app = create_app(Settings(api_keys=frozenset({"x"}), data_dir=Path(tmp)))
        schema: dict[str, Any] = app.openapi()
    return _problem_json(schema)


def _problem_json(schema: dict[str, Any]) -> dict[str, Any]:
    """Every error is application/problem+json; drop FastAPI's default 422 body shape."""
    ref = {"schema": {"$ref": "#/components/schemas/Problem"}}
    retry = {"Retry-After": {"description": "Seconds to wait", "schema": {"type": "integer"}}}
    for path in schema["paths"].values():
        for op in path.values():
            for code, resp in op["responses"].items():
                if code.isdigit() and int(code) >= 400:
                    resp["content"] = {"application/problem+json": ref}
                    if code == "422":
                        resp["description"] = "Invalid request"
                    if code in ("429", "503"):
                        resp["headers"] = retry
                if code == "202":
                    resp["description"] = "Accepted (new or reused job)"
                    resp["headers"] = {
                        "Location": {"description": "URL of the job", "schema": {"type": "string"}}
                    }
    for name in ("HTTPValidationError", "ValidationError"):
        schema["components"]["schemas"].pop(name, None)
    return schema


def render(schema: dict[str, Any]) -> str:
    return "# Generated by `python -m app.openapi_schema`. Do not edit by hand.\n" + yaml.safe_dump(
        schema, sort_keys=False, allow_unicode=True
    )


def main() -> int:
    text = render(build())
    if "--check" in sys.argv:
        if not SPEC_PATH.exists() or SPEC_PATH.read_text() != text:
            print("openapi.yaml is out of date: run `uv run python -m app.openapi_schema`")
            return 1
        print("openapi.yaml is up to date")
        return 0
    SPEC_PATH.write_text(text)
    print(f"wrote {SPEC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
